export enum FORM_FIELDS {
    FIRST_NAME = 'FirstName',
    LAST_NAME = 'LastName',
    FULL_NAME = 'FullName',
    EMAIL = 'Email',
    MOBILE_PHONE = 'MobilePhone',
    GENDER = 'Gender',
    HOME_PHONE = 'HomePhone',
    WORK_PHONE = 'WorkPhone',
    STREET_1 = 'Street1',
    STREET_2 = 'Street2',
    CITY = 'City',
    STATE = 'State',
    ZIP = 'Zip',
    COUNTRY = 'Country',
    BIRTHDAY = 'Birthday',
    COMPANY_NAME = 'CompanyName',
    WEB_SITE = 'WebSite',
    TITLE = 'Title',
}